package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"time"
)

// Customer represents a row from 'public.customer'.
type Customer struct {
	CustomerID int            `json:"customer_id"` // customer_id
	StoreID    int16          `json:"store_id"`    // store_id
	FirstName  string         `json:"first_name"`  // first_name
	LastName   string         `json:"last_name"`   // last_name
	Email      sql.NullString `json:"email"`       // email
	AddressID  int16          `json:"address_id"`  // address_id
	Activebool bool           `json:"activebool"`  // activebool
	CreateDate time.Time      `json:"create_date"` // create_date
	LastUpdate sql.NullTime   `json:"last_update"` // last_update
	Active     sql.NullInt64  `json:"active"`      // active
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Customer] exists in the database.
func (c *Customer) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Customer] has been marked for deletion
// from the database.
func (c *Customer) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Customer] to the database.
func (c *Customer) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.customer (` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`)`
	// run
	logf(sqlstr, c.CustomerID, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active)
	if _, err := db.ExecContext(ctx, sqlstr, c.CustomerID, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Customer] in the database.
func (c *Customer) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.customer SET ` +
		`store_id = $1, first_name = $2, last_name = $3, email = $4, address_id = $5, activebool = $6, create_date = $7, last_update = $8, active = $9 ` +
		`WHERE customer_id = $10`
	// run
	logf(sqlstr, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active, c.CustomerID)
	if _, err := db.ExecContext(ctx, sqlstr, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active, c.CustomerID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Customer] to the database.
func (c *Customer) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Customer].
func (c *Customer) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.customer (` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`)` +
		` ON CONFLICT (customer_id) DO ` +
		`UPDATE SET ` +
		`store_id = EXCLUDED.store_id, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, email = EXCLUDED.email, address_id = EXCLUDED.address_id, activebool = EXCLUDED.activebool, create_date = EXCLUDED.create_date, last_update = EXCLUDED.last_update, active = EXCLUDED.active `
	// run
	logf(sqlstr, c.CustomerID, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active)
	if _, err := db.ExecContext(ctx, sqlstr, c.CustomerID, c.StoreID, c.FirstName, c.LastName, c.Email, c.AddressID, c.Activebool, c.CreateDate, c.LastUpdate, c.Active); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Customer] from the database.
func (c *Customer) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.customer ` +
		`WHERE customer_id = $1`
	// run
	logf(sqlstr, c.CustomerID)
	if _, err := db.ExecContext(ctx, sqlstr, c.CustomerID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CustomerByCustomerID retrieves a row from 'public.customer' as a [Customer].
//
// Generated from index 'customer_pkey'.
func CustomerByCustomerID(ctx context.Context, db DB, customerID int) (*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active ` +
		`FROM public.customer ` +
		`WHERE customer_id = $1`
	// run
	logf(sqlstr, customerID)
	c := Customer{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, customerID).Scan(&c.CustomerID, &c.StoreID, &c.FirstName, &c.LastName, &c.Email, &c.AddressID, &c.Activebool, &c.CreateDate, &c.LastUpdate, &c.Active); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CustomerByAddressID retrieves a row from 'public.customer' as a [Customer].
//
// Generated from index 'idx_fk_address_id'.
func CustomerByAddressID(ctx context.Context, db DB, addressID int16) ([]*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active ` +
		`FROM public.customer ` +
		`WHERE address_id = $1`
	// run
	logf(sqlstr, addressID)
	rows, err := db.QueryContext(ctx, sqlstr, addressID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Customer
	for rows.Next() {
		c := Customer{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.CustomerID, &c.StoreID, &c.FirstName, &c.LastName, &c.Email, &c.AddressID, &c.Activebool, &c.CreateDate, &c.LastUpdate, &c.Active); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// CustomerByStoreID retrieves a row from 'public.customer' as a [Customer].
//
// Generated from index 'idx_fk_store_id'.
func CustomerByStoreID(ctx context.Context, db DB, storeID int16) ([]*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active ` +
		`FROM public.customer ` +
		`WHERE store_id = $1`
	// run
	logf(sqlstr, storeID)
	rows, err := db.QueryContext(ctx, sqlstr, storeID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Customer
	for rows.Next() {
		c := Customer{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.CustomerID, &c.StoreID, &c.FirstName, &c.LastName, &c.Email, &c.AddressID, &c.Activebool, &c.CreateDate, &c.LastUpdate, &c.Active); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// CustomerByLastName retrieves a row from 'public.customer' as a [Customer].
//
// Generated from index 'idx_last_name'.
func CustomerByLastName(ctx context.Context, db DB, lastName string) ([]*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active ` +
		`FROM public.customer ` +
		`WHERE last_name = $1`
	// run
	logf(sqlstr, lastName)
	rows, err := db.QueryContext(ctx, sqlstr, lastName)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Customer
	for rows.Next() {
		c := Customer{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.CustomerID, &c.StoreID, &c.FirstName, &c.LastName, &c.Email, &c.AddressID, &c.Activebool, &c.CreateDate, &c.LastUpdate, &c.Active); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// Address returns the Address associated with the [Customer]'s (AddressID).
//
// Generated from foreign key 'customer_address_id_fkey'.
func (c *Customer) Address(ctx context.Context, db DB) (*Address, error) {
	return AddressByAddressID(ctx, db, int(c.AddressID))
}
