package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// Inventory represents a row from 'public.inventory'.
type Inventory struct {
	InventoryID int       `json:"inventory_id"` // inventory_id
	FilmID      int16     `json:"film_id"`      // film_id
	StoreID     int16     `json:"store_id"`     // store_id
	LastUpdate  time.Time `json:"last_update"`  // last_update
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Inventory] exists in the database.
func (i *Inventory) Exists() bool {
	return i._exists
}

// Deleted returns true when the [Inventory] has been marked for deletion
// from the database.
func (i *Inventory) Deleted() bool {
	return i._deleted
}

// Insert inserts the [Inventory] to the database.
func (i *Inventory) Insert(ctx context.Context, db DB) error {
	switch {
	case i._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case i._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.inventory (` +
		`inventory_id, film_id, store_id, last_update` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`
	// run
	logf(sqlstr, i.InventoryID, i.FilmID, i.StoreID, i.LastUpdate)
	if _, err := db.ExecContext(ctx, sqlstr, i.InventoryID, i.FilmID, i.StoreID, i.LastUpdate); err != nil {
		return logerror(err)
	}
	// set exists
	i._exists = true
	return nil
}

// Update updates a [Inventory] in the database.
func (i *Inventory) Update(ctx context.Context, db DB) error {
	switch {
	case !i._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case i._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.inventory SET ` +
		`film_id = $1, store_id = $2, last_update = $3 ` +
		`WHERE inventory_id = $4`
	// run
	logf(sqlstr, i.FilmID, i.StoreID, i.LastUpdate, i.InventoryID)
	if _, err := db.ExecContext(ctx, sqlstr, i.FilmID, i.StoreID, i.LastUpdate, i.InventoryID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Inventory] to the database.
func (i *Inventory) Save(ctx context.Context, db DB) error {
	if i.Exists() {
		return i.Update(ctx, db)
	}
	return i.Insert(ctx, db)
}

// Upsert performs an upsert for [Inventory].
func (i *Inventory) Upsert(ctx context.Context, db DB) error {
	switch {
	case i._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.inventory (` +
		`inventory_id, film_id, store_id, last_update` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)` +
		` ON CONFLICT (inventory_id) DO ` +
		`UPDATE SET ` +
		`film_id = EXCLUDED.film_id, store_id = EXCLUDED.store_id, last_update = EXCLUDED.last_update `
	// run
	logf(sqlstr, i.InventoryID, i.FilmID, i.StoreID, i.LastUpdate)
	if _, err := db.ExecContext(ctx, sqlstr, i.InventoryID, i.FilmID, i.StoreID, i.LastUpdate); err != nil {
		return logerror(err)
	}
	// set exists
	i._exists = true
	return nil
}

// Delete deletes the [Inventory] from the database.
func (i *Inventory) Delete(ctx context.Context, db DB) error {
	switch {
	case !i._exists: // doesn't exist
		return nil
	case i._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.inventory ` +
		`WHERE inventory_id = $1`
	// run
	logf(sqlstr, i.InventoryID)
	if _, err := db.ExecContext(ctx, sqlstr, i.InventoryID); err != nil {
		return logerror(err)
	}
	// set deleted
	i._deleted = true
	return nil
}

// InventoryByStoreIDFilmID retrieves a row from 'public.inventory' as a [Inventory].
//
// Generated from index 'idx_store_id_film_id'.
func InventoryByStoreIDFilmID(ctx context.Context, db DB, storeID, filmID int16) ([]*Inventory, error) {
	// query
	const sqlstr = `SELECT ` +
		`inventory_id, film_id, store_id, last_update ` +
		`FROM public.inventory ` +
		`WHERE store_id = $1 AND film_id = $2`
	// run
	logf(sqlstr, storeID, filmID)
	rows, err := db.QueryContext(ctx, sqlstr, storeID, filmID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Inventory
	for rows.Next() {
		i := Inventory{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&i.InventoryID, &i.FilmID, &i.StoreID, &i.LastUpdate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// InventoryByInventoryID retrieves a row from 'public.inventory' as a [Inventory].
//
// Generated from index 'inventory_pkey'.
func InventoryByInventoryID(ctx context.Context, db DB, inventoryID int) (*Inventory, error) {
	// query
	const sqlstr = `SELECT ` +
		`inventory_id, film_id, store_id, last_update ` +
		`FROM public.inventory ` +
		`WHERE inventory_id = $1`
	// run
	logf(sqlstr, inventoryID)
	i := Inventory{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, inventoryID).Scan(&i.InventoryID, &i.FilmID, &i.StoreID, &i.LastUpdate); err != nil {
		return nil, logerror(err)
	}
	return &i, nil
}

// Film returns the Film associated with the [Inventory]'s (FilmID).
//
// Generated from foreign key 'inventory_film_id_fkey'.
func (i *Inventory) Film(ctx context.Context, db DB) (*Film, error) {
	return FilmByFilmID(ctx, db, int(i.FilmID))
}
