package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// FilmNotInStock calls the stored function 'public.film_not_in_stock(integer, integer) integer' on db.
func FilmNotInStock(ctx context.Context, db DB, pFilmID, pStoreID int) (int, error) {
	// call public.film_not_in_stock
	const sqlstr = `SELECT * FROM public.film_not_in_stock($1, $2)`
	// run
	var pFilmCount int
	logf(sqlstr, pFilmID, pStoreID)
	if err := db.QueryRowContext(ctx, sqlstr, pFilmID, pStoreID).Scan(&pFilmCount); err != nil {
		return 0, logerror(err)
	}
	return pFilmCount, nil
}
