package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// GroupConcat calls the stored function 'public._group_concat(text, text) text' on db.
func GroupConcat(ctx context.Context, db DB, p0, p1 string) (string, error) {
	// call public._group_concat
	const sqlstr = `SELECT * FROM public._group_concat($1, $2)`
	// run
	var r0 string
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
