package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// InventoryInStock calls the stored function 'public.inventory_in_stock(integer) boolean' on db.
func InventoryInStock(ctx context.Context, db DB, pInventoryID int) (bool, error) {
	// call public.inventory_in_stock
	const sqlstr = `SELECT * FROM public.inventory_in_stock($1)`
	// run
	var r0 bool
	logf(sqlstr, pInventoryID)
	if err := db.QueryRowContext(ctx, sqlstr, pInventoryID).Scan(&r0); err != nil {
		return false, logerror(err)
	}
	return r0, nil
}
