package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// LastDay calls the stored function 'public.last_day(timestamp without time zone) date' on db.
func LastDay(ctx context.Context, db DB, p0 time.Time) (time.Time, error) {
	// call public.last_day
	const sqlstr = `SELECT * FROM public.last_day($1)`
	// run
	var r0 time.Time
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return time.Time{}, logerror(err)
	}
	return r0, nil
}
