package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// LastUpdated calls the stored function 'public.last_updated() trigger' on db.
func LastUpdated(ctx context.Context, db DB) (Trigger, error) {
	// call public.last_updated
	const sqlstr = `SELECT * FROM public.last_updated()`
	// run
	var r0 Trigger
	logf(sqlstr)
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
